# permissions for end users to edit notifyservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-notify-oparator
    app.kubernetes.io/managed-by: kustomize
  name: notifyservice-editor-role
rules:
- apiGroups:
  - k8s-notify.jalilb.dev
  resources:
  - notifyservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-notify.jalilb.dev
  resources:
  - notifyservices/status
  verbs:
  - get
